---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-view-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-view-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal-account
automountServiceAccountToken: false

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-svc-account
subjects:
  - kind: ServiceAccount
    name: terminal-account
roleRef:
  kind: Role
  name: pod-view-role
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-exec-svc-account
subjects:
  - kind: ServiceAccount
    name: terminal-account
roleRef:
  kind: Role
  name: pod-exec-view-role
  apiGroup: rbac.authorization.k8s.io
